
import React from 'react';
import { Icons } from '../constants.tsx';

const Trust: React.FC = () => {
  return (
    <div className="bg-slate-50 min-h-screen py-24">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <header className="mb-20 text-center lg:text-left">
          <div className="inline-flex items-center gap-2 px-4 py-1 rounded-full bg-blue-100 text-blue-700 text-xs font-bold uppercase tracking-widest mb-6">
            <Icons.Shield /> Regulatory & Ethics Framework
          </div>
          <h1 className="text-5xl font-bold text-slate-900 mb-6 tracking-tight">Trust by Design</h1>
          <p className="text-xl text-slate-600 leading-relaxed max-w-2xl">
            BITARA LAB maintains an uncompromising commitment to data ethics, regulatory transparency, and legal clarity in probabilistic intelligence.
          </p>
        </header>

        <div className="space-y-12">
          {/* Institutional Logging */}
          <section className="bg-white rounded-[2rem] p-10 border border-slate-200 shadow-sm">
            <div className="flex items-center gap-4 mb-6">
              <div className="p-3 bg-green-50 text-green-600 rounded-xl"><Icons.Database /></div>
              <h2 className="text-2xl font-bold text-slate-900">Institutional Audit Logging</h2>
            </div>
            <div className="prose prose-slate max-w-none text-slate-600 space-y-6">
              <p>
                As part of our commitment to transparency, Bitara Lab utilizes an <strong>Immutable Audit Trail</strong>. Every probabilistic query performed by authorized users is automatically logged into a secure institutional storage layer (hosted via Google Sheets for multi-stakeholder visibility).
              </p>
              <ul className="text-sm space-y-2">
                <li className="flex gap-2 font-bold text-slate-700"><span>•</span> Automatic timestamping of every query.</li>
                <li className="flex gap-2 font-bold text-slate-700"><span>•</span> Full retention of signal weightage at time of query.</li>
                <li className="flex gap-2 font-bold text-slate-700"><span>•</span> Centralized access for bank compliance officers and regulators.</li>
              </ul>
            </div>
          </section>

          {/* Probabilistic Philosophy */}
          <section className="bg-white rounded-[2rem] p-10 border border-slate-200 shadow-sm">
            <h2 className="text-2xl font-bold text-slate-900 mb-6">1. Probabilistic Philosophy</h2>
            <div className="prose prose-slate max-w-none text-slate-600 space-y-6">
              <p>
                The fundamental distinction of the Bitara platform is our focus on <strong>probability</strong> rather than <strong>blacklisting</strong>. By quantifying risk as a variable index (0–100), we empower our clients to apply their own risk appetite and operational thresholds.
              </p>
              <div className="bg-slate-900 p-8 rounded-2xl text-white relative overflow-hidden">
                <div className="relative z-10 italic text-lg opacity-90">
                  "Deterministic labels ('Scam') create legal friction; probabilistic signals ('Risk Score') enable compliance agility."
                </div>
                <div className="absolute top-0 right-0 p-4 opacity-10">
                  <Icons.Activity />
                </div>
              </div>
            </div>
          </section>

          {/* Legal Disclaimer */}
          <section className="bg-blue-600 rounded-[2rem] p-10 text-white shadow-xl relative overflow-hidden">
            <div className="absolute inset-0 bg-blue-700 mix-blend-multiply opacity-20 pointer-events-none"></div>
            <div className="relative z-10">
              <h2 className="text-xl font-bold mb-6 flex items-center gap-2 uppercase tracking-widest text-blue-100">
                <Icons.Shield /> Mandatory Compliance Disclosure
              </h2>
              <p className="text-sm leading-relaxed opacity-90 mb-8 font-medium">
                BITARA LAB operates as a Data-as-a-Service (DaaS) provider. The scores and indicators generated by the platform are purely probabilistic and represent the likelihood of association with high-risk behavioral patterns. 
                <br /><br />
                BITARA LAB does not hold authority as a judicial body or law enforcement agency. All final operational decisions—including transaction blocking, account suspension, or reporting—are the sole responsibility of the Client organization.
              </p>
              <div className="flex flex-wrap gap-4">
                <a 
                  href="https://docs.google.com/spreadsheets/d/17kWihP5Zuy_4wvf614FlgO2aZJi7UfHsDIF6tUobajU/edit?usp=sharing" 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="px-6 py-2 bg-white text-blue-600 rounded-lg text-xs font-bold uppercase tracking-widest hover:bg-blue-50 transition-colors"
                >
                  View Audit Sheet
                </a>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
};

export default Trust;
